import { MAIN_AFFIXS, GROW_VALUE, SINGLE_VALUE, SUB_AFFIXS, RANK_MAP, ELEM, POS, SKILL, DMG, PROP } from './getConstLet.js'

export { MAIN_AFFIXS, GROW_VALUE, SINGLE_VALUE, SUB_AFFIXS, RANK_MAP, ELEM, POS, SKILL, DMG, PROP }
