import {getPinyin, pinyin} from "./getPinyin.js";

export async function cxbz(e) {
    await e.reply(`抽象话转换帮助\n\n\n将xxx转换为抽象话\n抽象（cx）xxx\n\n将xxx抽象话还原成拼音\n还抽（hc）xxx\n\n将xxx转为化学元素\n化学（hx）xxx\n\n将汉字xxx转为拼音\n转拼（zp）xxx`)
    return true
}

export async function cx(e) {
    let Msg = e.original_msg || e.msg
    let text = Msg.replace(/抽象|#|cx/g, '').trim();
    let msg = await chouxiang(text);
    await e.reply(msg)
    return true
}

export async function hc(e) {
    let Msg = e.original_msg || e.msg
    let text = Msg.replace(/还抽|#|hc/g, '').trim();
    let text1 = await dechouxiang1(text);
    let msg = await dechouxiang2(text1)
    await e.reply(msg)
    return true
}

export async function hx(e) {
    let Msg = e.original_msg || e.msg
    let text = Msg.replace(/化学|#|hx/g, '').trim();
    let msg = await huaxue(text);
    await e.reply(msg)
    return true
}

export async function zp(e) {
    let Msg = e.original_msg || e.msg
    let text = Msg.replace(/转拼|#|zp/g, '').trim();
    let msg = await zhuanpinyin(text);
    await e.reply(msg)
    return true
}

const emoji = {
    "0": "0⃣",
    "ling": "0⃣",
    "one": "1⃣",
    "1": "1⃣",
    "yi": "1⃣",
    "two": "2⃣",
    "2": "2⃣",
    "er": "2⃣",
    "three": "3⃣",
    "3": "3⃣",
    "san": "3⃣",
    "4": "4⃣",
    "si": "4⃣",
    "four": "4⃣",
    "5": "5⃣",
    "wu": "5⃣",
    "five": "5⃣",
    "liu": "6⃣",
    "six": "6⃣",
    "6": "6⃣",
    "qi": "7⃣",
    "7": "7⃣",
    "seven": "7⃣",
    "eight": "8⃣",
    "ba": "8⃣",
    "8": "8⃣",
    "bu": "8️⃣",
    "nine": "9⃣",
    "jiu": "9⃣",
    "9": "9⃣",
    "?": "¿",
    "？": "¿",
    "tama": "™",
    "tema": "™",
    "zuoyou": "↔",
    "shangxia": "↕",
    "zuoshang": "↖",
    "youshang": "↗",
    "youxia": "↘",
    "zuoxia": "↙",
    "biao": "⌚",
    "shalou": "⌛",
    "sha": "⌛",
    "jianpan": "⌨",
    "tuichu": "⏏",
    "kuaijin": "⏩",
    "qianjin": "⏩",
    "kuaitui": "⏪",
    "houtui": "⏪",
    "xu": "⏭",
    "naozhong": "⏰",
    "zhong": "⏰",
    "zanting": "⏹",
    "kai": "▶",
    "bofang": "▶",
    "fanhuijian": "◀",
    "taiyang": "☀",
    "ri": "☀️",
    "taiyang": "☀️",
    "yintian": "☁",
    "yun": "☁️",
    "san": "☂️",
    "yusan": "☂️",
    "xueren": "☃️",
    "zhuang": "☄",
    "dianhua": "☎",
    "xiayu": "☔",
    "cha": "☕",
    "yi": "☝",
    "du": "☠",
    "fushe": "☢",
    "musilin": "☪",
    "qingzhen": "☪",
    "yisilan": "☪",
    "yinyang": "☯",
    "nv": "♀",
    "nan": "♂",
    "baiyangzuo": "♈",
    "jinniuzuo": "♉",
    "shuangzizuo": "♊",
    "juxiezuo": "♋",
    "shizizuo": "♌",
    "chunüzuo": "♍",
    "tianchengzuo": "♎",
    "tianxiezuo": "♏",
    "sheshouzuo": "♐",
    "mojiezuo": "♑",
    "shuipingzuo": "♒",
    "shuangyuzuo": "♓",
    "heitao": "♠",
    "meihua": "♣",
    "hongtao": "♥",
    "fangkuai": "♦",
    "fangpian": "♦",
    "zheng": "♨",
    "java": "♨",
    "huishou": "♻",
    "wuxian": "♾",
    "wuqiong": "♾",
    "lunyi": "♿",
    "canjiren": "♿",
    "tianping": "⚖",
    "chilun": "⚙",
    "yuanzi": "⚛",
    "jinggao": "⚠",
    "gaoyadian": "⚡",
    "dian": "⚡",
    "shandian": "⚡",
    "zuqiu": "⚽",
    "qiu": "⚽",
    "bangqiu": "⚾",
    "xueren": "⛄",
    "duoyun": "⛅",
    "shefuzuo": "⛎",
    "zao": "⛏",
    "dai": "⛑",
    "suolian": "⛓",
    "jinzhijinru": "⛔",
    "shan": "⛰️",
    "huaxue": "⛷️",
    "daqiu": "⛹️",
    "jiayou": "⛽",
    "jiayouzhan": "⛽",
    "jian": "✂",
    "jiandao": "✂",
    "dui": "✅",
    "feiji": "✈",
    "feiji": "✈️",
    "xinfeng": "✉",
    "xin": "✉",
    "shou": "✊",
    "zhang": "✋",
    "yeah": "✌",
    "ye": "✌️",
    "jiandaoshou": "✌️",
    "qianbi": "✏",
    "xing": "✨",
    "shan": "✨",
    "xuehua": "❄️",
    "xue": "❄️",
    "cuo": "❌",
    "!": "❕",
    "！": "❕",
    "!": "❗",
    "ai": "❤",
    "jia": "➕",
    "jian": "➖",
    "chu": "➗",
    "you": "➡",
    "xian": "➰",
    "zuo": "⬅",
    "shang": "⬆",
    "xia": "⬇",
    "xing": "⭐",
    "hang": "⭐",
    "o": "⭕",
    "quan": "⭕",
    "huan": "⭕",
    "yuan": "⭕",
    "zhu": "㊗",
    "mi": "㊙",
    "hongzhong": "🀄",
    "zhong": "🀄",
    "pian": "🃏",
    "puke": "🃏",
    "pai": "🃏",
    "a": "🅰",
    "b": "🅱",
    "ou": "🅾",
    "ab": "🆎",
    "ku": "🆒",
    "mianfei": "🆓",
    "shenfen": "🆔",
    "xin": "🆕",
    "new": "🆕",
    "ok": "🆗",
    "cheng": "🆗",
    "up": "🆙",
    "jiaoliang": "🆚",
    "asensongdao": "🇦🇨",
    "andaoer": "🇦🇩",
    "alianqiu": "🇦🇪",
    "afuhan": "🇦🇫",
    "antiguahebabuda": "🇦🇬",
    "anguila": "🇦🇮",
    "aerbaniya": "🇦🇱",
    "yameiniya": "🇦🇲",
    "angela": "🇦🇴",
    "nanjizhou": "🇦🇶",
    "agenting": "🇦🇷",
    "meishusamoyaqundao": "🇦🇸",
    "aodili": "🇦🇹",
    "aodaliya": "🇦🇺",
    "aluba": "🇦🇼",
    "aolanqundao": "🇦🇽",
    "asaibaijiang": "🇦🇿",
    "bohei": "🇧🇦",
    "baduosi": "🇧🇧",
    "mengjialaguo": "🇧🇩",
    "weibilishi": "🇧🇪",
    "bujinafasuo": "🇧🇫",
    "baojialiya": "🇧🇬",
    "balin": "🇧🇭",
    "bulongdi": "🇧🇮",
    "beining": "🇧🇯",
    "shengbatailemi": "🇧🇱",
    "baimuda": "🇧🇲",
    "wenlai": "🇧🇳",
    "boliweiya": "🇧🇴",
    "helanjialebi": "🇧🇶",
    "baxi": "🇧🇷",
    "bahama": "🇧🇸",
    "budan": "🇧🇹",
    "buweidao": "🇧🇻",
    "bociwana": "🇧🇼",
    "baieluosi": "🇧🇾",
    "bolizi": "🇧🇿",
    "jianada": "🇨🇦",
    "kekesiqundao": "🇨🇨",
    "gangguojin": "🇨🇩",
    "zhongfeigongheguo": "🇨🇫",
    "gangguobu": "🇨🇬",
    "ruishi": "🇨🇭",
    "ketediwa": "🇨🇮",
    "kukequndao": "🇨🇰",
    "zhili": "🇨🇱",
    "kamailong": "🇨🇲",
    "zhongguo": "🇨🇳",
    "gelunbiya": "🇨🇴",
    "kelipodundao": "🇨🇵",
    "gesidalijia": "🇨🇷",
    "guba": "🇨🇺",
    "fodejiao": "🇨🇻",
    "kulasuo": "🇨🇼",
    "shengdandao": "🇨🇽",
    "saipulusi": "🇨🇾",
    "jiekegongheguo": "🇨🇿",
    "deguo": "🇩🇪",
    "digejiaxiya": "🇩🇬",
    "jibuti": "🇩🇯",
    "danmai": "🇩🇰",
    "duominijia": "🇩🇲",
    "duomingnijiagongheguo": "🇩🇴",
    "aerjiliya": "🇩🇿",
    "xiudahemeililiya": "🇪🇦",
    "eguaduoer": "🇪🇨",
    "aishaniya": "🇪🇪",
    "aiji": "🇪🇬",
    "xisahala": "🇪🇭",
    "eliteliya": "🇪🇷",
    "xibanya": "🇪🇸",
    "aisaiebiya": "🇪🇹",
    "oumeng": "🇪🇺",
    "fenlan": "🇫🇮",
    "feiji": "🇫🇯",
    "fukelanqundao": "🇫🇰",
    "mikeluonixiya": "🇫🇲",
    "faluoqundao": "🇫🇴",
    "faguo": "🇫🇷",
    "jiapeng": "🇬🇦",
    "yingguo": "🇬🇧",
    "gelinnada": "🇬🇩",
    "gelujiya": "🇬🇪",
    "fashuguiyana": "🇬🇫",
    "genxidao": "🇬🇬",
    "jiana": "🇬🇭",
    "zhibuluotuo": "🇬🇮",
    "gelinglan": "🇬🇱",
    "gangbiya": "🇬🇲",
    "jineiya": "🇬🇳",
    "guadeluopudao": "🇬🇵",
    "chidaojineiya": "🇬🇶",
    "xila": "🇬🇷",
    "nanqiaozhiyadaohenansangweiqiqundao": "🇬🇸",
    "weidimala": "🇬🇹",
    "guandao": "🇬🇺",
    "jineiyabishao": "🇬🇼",
    "guiyana": "🇬🇾",
    "xianggang": "🇭🇰",
    "hedeyumaiketangnaqundao": "🇭🇲",
    "hongdoulasi": "🇭🇳",
    "keluodiya": "🇭🇷",
    "haidi": "🇭🇹",
    "xiongyali": "🇭🇺",
    "jianaliqundao": "🇮🇨",
    "yinni": "🇮🇩",
    "aierlan": "🇮🇪",
    "weiyiselie": "🇮🇱",
    "mandao": "🇮🇲",
    "yindu": "🇮🇳",
    "yingshuyinduyanglingdi": "🇮🇴",
    "yilake": "🇮🇶",
    "yilang": "🇮🇷",
    "bingdao": "🇮🇸",
    "yidali": "🇮🇹",
    "zexi": "🇯🇪",
    "yamaijia": "🇯🇲",
    "yuedan": "🇯🇴",
    "riben": "🇯🇵",
    "kenniya": "🇰🇪",
    "jierjisisitan": "🇰🇬",
    "jianpuzhai": "🇰🇭",
    "jilibasi": "🇰🇮",
    "kemoluo": "🇰🇲",
    "shengjiciheniweisi": "🇰🇳",
    "chaoxian": "🇰🇵",
    "hanguo": "🇰🇷",
    "keweite": "🇰🇼",
    "kaimanqundao": "🇰🇾",
    "hasakesitan": "🇰🇿",
    "laowo": "🇱🇦",
    "libanen": "🇱🇧",
    "shengluxiya": "🇱🇨",
    "liezhidunshideng": "🇱🇮",
    "sililanka": "🇱🇰",
    "libiliya": "🇱🇷",
    "laisuotuo": "🇱🇸",
    "litaowan": "🇱🇹",
    "lusenbao": "🇱🇺",
    "latuoweiya": "🇱🇻",
    "libiya": "🇱🇾",
    "moluoge": "🇲🇦",
    "monage": "🇲🇨",
    "moerduowa": "🇲🇩",
    "heishan": "🇲🇪",
    "shengmading": "🇲🇫",
    "madajiasijia": "🇲🇬",
    "mashaoerqundao": "🇲🇭",
    "maqidun": "🇲🇰",
    "mali": "🇲🇱",
    "miandian": "🇲🇲",
    "menggu": "🇲🇳",
    "aomen": "🇲🇴",
    "beimaliyanaqundao": "🇲🇵",
    "matinikedao": "🇲🇶",
    "maolitaniya": "🇲🇷",
    "mengtesailate": "🇲🇸",
    "maerta": "🇲🇹",
    "maoliqiusi": "🇲🇺",
    "maerdaifu": "🇲🇻",
    "malawei": "🇲🇼",
    "moxige": "🇲🇽",
    "malaixiya": "🇲🇾",
    "mosangbike": "🇲🇿",
    "namibiya": "🇳🇦",
    "xinkaliduoniya": "🇳🇨",
    "nirier": "🇳🇪",
    "nuofukedao": "🇳🇫",
    "niriliya": "🇳🇬",
    "nijialagua": "🇳🇮",
    "helan": "🇳🇱",
    "nuowei": "🇳🇴",
    "niboer": "🇳🇵",
    "naolu": "🇳🇷",
    "niuai": "🇳🇺",
    "xinxilan": "🇳🇿",
    "aman": "🇴🇲",
    "banama": "🇵🇦",
    "milu": "🇵🇪",
    "fashubolinixiya": "🇵🇫",
    "babuyaxinjineiya": "🇵🇬",
    "feilübin": "🇵🇭",
    "bajisitan": "🇵🇰",
    "bolan": "🇵🇱",
    "shengpiaierhemikelongqundao": "🇵🇲",
    "pitekaienqundao": "🇵🇳",
    "boduolige": "🇵🇷",
    "balesitanlingtu": "🇵🇸",
    "putaoya": "🇵🇹",
    "palao": "🇵🇼",
    "balagui": "🇵🇾",
    "kataer": "🇶🇦",
    "tuanyuan": "🇷🇪",
    "luomaniya": "🇷🇴",
    "saierweiya": "🇷🇸",
    "eluosi": "🇷🇺",
    "luwangda": "🇷🇼",
    "shatealabo": "🇸🇦",
    "suoluomenqundao": "🇸🇧",
    "saisheer": "🇸🇨",
    "sudan": "🇸🇩",
    "ruidian": "🇸🇪",
    "xinjiapo": "🇸🇬",
    "shenghelena": "🇸🇭",
    "siluowenniya": "🇸🇮",
    "siwaerbaqundaoheyangmayan": "🇸🇯",
    "siluofake": "🇸🇰",
    "sailaliang": "🇸🇱",
    "shengmalinuo": "🇸🇲",
    "saineijiaer": "🇸🇳",
    "suomali": "🇸🇴",
    "sulinan": "🇸🇷",
    "nansudan": "🇸🇸",
    "shengduomeihepulinxibi": "🇸🇹",
    "saerwaduo": "🇸🇻",
    "shengmadingdao": "🇸🇽",
    "xuliya": "🇸🇾",
    "siweishilan": "🇸🇿",
    "telisitandakuniyaqundao": "🇹🇦",
    "tekesihekaikesiqundao": "🇹🇨",
    "zhade": "🇹🇩",
    "faguonanfangdelingtu": "🇹🇫",
    "duoge": "🇹🇬",
    "taiguo": "🇹🇭",
    "tajikesitan": "🇹🇯",
    "tuokelao": "🇹🇰",
    "dongdiwen": "🇹🇱",
    "tukumansitan": "🇹🇲",
    "tunisi": "🇹🇳",
    "tangjia": "🇹🇴",
    "tuerqi": "🇹🇷",
    "telinidaheduobage": "🇹🇹",
    "tuwalu": "🇹🇻",
    "taiwan": "🇹🇼",
    "tansangniya": "🇹🇿",
    "wukelan": "🇺🇦",
    "wuganda": "🇺🇬",
    "meiguolidao": "🇺🇲",
    "mei": "🇺🇸",
    "meiguo": "🇺🇸",
    "wulagui": "🇺🇾",
    "wuzibiekesitan": "🇺🇿",
    "fandigangcheng": "🇻🇦",
    "shengwensentehegelinnadingsi": "🇻🇨",
    "weineiruila": "🇻🇪",
    "yingshuweierjingqundao": "🇻🇬",
    "meishuweierjingqundao": "🇻🇮",
    "yuenan": "🇻🇳",
    "wanuatu": "🇻🇺",
    "walisihefutunaqundao": "🇼🇫",
    "samoya": "🇼🇸",
    "kesuowo": "🇽🇰",
    "yemen": "🇾🇪",
    "mayuete": "🇾🇹",
    "nanfei": "🇿🇦",
    "zanbiya": "🇿🇲",
    "jinbabuwei": "🇿🇼",
    "wu": "🈚",
    "zhi": "🈯",
    "jin": "🈲",
    "kong": "🈳",
    "heshi": "🈴",
    "man": "🈵",
    "you": "🈶",
    "yue": "🈷",
    "shen": "🈸",
    "ge": "🈹",
    "gong": "🈺",
    "de": "🉐",
    "ke": "🉑",
    "xuanfeng": "🌀",
    "jufeng": "🌀",
    "yusan": "🌂",
    "chen": "🌅",
    "caihong": "🌈",
    "bo": "🌊",
    "lang": "🌊",
    "bolang": "🌊",
    "haihang": "🌊⭐",
    "huoshan": "🌋",
    "shijie": "🌏",
    "diqiu": "🌏",
    "yue": "🌙",
    "yueliang": "🌙",
    "tai": "🌞",
    "ri": "🌞",
    "taiyang": "🌞",
    "mingxing": "🌟",
    "xing": "🌟",
    "liuxing": "🌠",
    "hui": "🌠",
    "wenduji": "🌡",
    "zhe": "🌤",
    "xiayu": "🌧️",
    "yu": "🌧️",
    "xiaxue": "🌨️",
    "longjuanfeng": "🌪️",
    "wu": "🌫️",
    "regou": "🌭",
    "huotui": "🌭",
    "shu": "🌲",
    "xianrenzhang": "🌵",
    "na": "🌶",
    "la": "🌶",
    "la": "🌶️",
    "na": "🌶️",
    "lajiao": "🌶️",
    "le": "🌶️",
    "hua": "🌸",
    "xianhua": "🌸",
    "yinghua": "🌸",
    "huaduo": "🌸",
    "meigui": "🌹",
    "xiangrikui": "🌻",
    "tou": "🌿",
    "cao": "🌿",
    "siyecao": "🍀",
    "fengye": "🍁",
    "luoye": "🍂",
    "gu": "🍄",
    "mogu": "🍄",
    "xihongshi": "🍅",
    "que": "🍆",
    "qie": "🍆",
    "qiezi": "🍆",
    "putao": "🍇",
    "gua": "🍉",
    "xigua": "🍉",
    "juzi": "🍊",
    "ju": "🍊",
    "suan": "🍋",
    "ningmeng": "🍋",
    "jiao": "🍌",
    "xiangjiao": "🍌",
    "boluo": "🍍",
    "fengli": "🍍",
    "ping": "🍎",
    "pingguo": "🍎",
    "pinglun": "🍎🚢",
    "li": "🍐",
    "lizi": "🍐",
    "taozi": "🍑",
    "tao": "🍑",
    "yingtao": "🍒",
    "caomei": "🍓",
    "hanbao": "🍔",
    "hanbaobao": "🍔",
    "han": "🍔",
    "pisa": "🍕",
    "rou": "🍖",
    "jitui": "🍗",
    "fantuan": "🍙",
    "fan": "🍚",
    "mifan": "🍚",
    "mian": "🍜",
    "miantiao": "🍜",
    "miantiao": "🍝",
    "ban": "🍝",
    "mianbao": "🍞",
    "shutiao": "🍟",
    "wan": "🍡",
    "shousi": "🍣",
    "sharen": "🍤",
    "xiaren": "🍤",
    "bingjilin": "🍦",
    "bingqilin": "🍦",
    "bin": "🍦",
    "shengdai": "🍧",
    "dong": "🍩",
    "quqi": "🍪",
    "qiaokelibang": "🍫",
    "qiaokeli": "🍫",
    "tang": "🍬",
    "tiantianquan": "🍭",
    "yikuaidangao": "🍰",
    "jiandan": "🍳",
    "jian": "🍳",
    "canju": "🍴",
    "chazi": "🍴",
    "jiubei": "🍷",
    "pi": "🍺",
    "pijiu": "🍺",
    "bi": "🍺",
    "jiu": "🍺",
    "ganbei": "🍻",
    "lai": "🍼",
    "naiping": "🍼",
    "nai": "🍼",
    "baomihua": "🍿",
    "hudiejie": "🎀",
    "jie": "🎀",
    "liwu": "🎁",
    "li": "🎁",
    "dangao": "🎂",
    "shengridangao": "🎂",
    "nangua": "🎃",
    "shengdanshu": "🎄",
    "shengdanlaoren": "🎅",
    "shengdan": "🎅",
    "yanhua": "🎆",
    "qiqiu": "🎈",
    "qing": "🎈",
    "gongxi": "🎉",
    "zhuhe": "🎉",
    "xi": "🎊",
    "ribenren": "🎎",
    "liyuqi": "🎏",
    "shubao": "🎒",
    "xunzhang": "🎖️",
    "motianlun": "🎡",
    "po": "🎢",
    "guoshanche": "🎢",
    "yugan": "🎣",
    "diaoyu": "🎣",
    "changge": "🎤",
    "huatong": "🎤",
    "sheyingji": "🎥",
    "shengxiangji": "🎥",
    "dianyingyuan": "🎦",
    "tingyinyue": "🎧",
    "erji": "🎧",
    "hua": "🎨",
    "yishu": "🎨",
    "yanse": "🎨",
    "huaban": "🎨",
    "gaomao": "🎩",
    "maozi": "🎩",
    "piao": "🎫",
    "dianying": "🎬",
    "jianji": "🎬",
    "dayouxi": "🎮",
    "youxi": "🎮",
    "mingzhong": "🎯",
    "taiqiu": "🎱",
    "ba": "🎱",
    "touzi": "🎲",
    "sezi": "🎲",
    "baolingqiu": "🎳",
    "yinle": "🎵",
    "yin": "🎵",
    "yinyue": "🎶",
    "sakesi": "🎷",
    "jita": "🎸",
    "gangqin": "🎹",
    "xiaotiqin": "🎻",
    "qu": "🎼",
    "wangqiu": "🎾",
    "huaxue": "🎿",
    "qiu": "🏀",
    "lanqiu": "🏀",
    "paobu": "🏃",
    "pao": "🏃",
    "benpao": "🏃💨",
    "chonglang": "🏄",
    "jiangpai": "🏅",
    "jin": "🏆",
    "guanjun": "🏆",
    "jiangbei": "🏆",
    "qima": "🏇",
    "ganlanqiu": "🏈",
    "you": "🏊",
    "youyong": "🏊",
    "juzhong": "🏋️",
    "motuoche": "🏍️",
    "motuo": "🏍️",
    "saiche": "🏎️",
    "paiqiu": "🏐",
    "pingpangqiu": "🏓",
    "shan": "🏔",
    "fangzi": "🏠",
    "jiating": "🏠",
    "haosi": "🏠",
    "yiyuan": "🏥",
    "yinhang": "🏦",
    "qukuanji": "🏧",
    "ATM": "🏧",
    "binguan": "🏨",
    "lüguan": "🏨",
    "yiyuan": "🏨",
    "yiyuan": "🏩",
    "jiudian": "🏪",
    "xuexiao": "🏫",
    "biaoqian": "🏷",
    "yumaoqiu": "🏸",
    "shejian": "🏹",
    "bao": "🐆",
    "tu": "🐇",
    "jing": "🐋",
    "jingyu": "🐋",
    "woniu": "🐌",
    "she": "🐍",
    "ma": "🐎",
    "yang": "🐑",
    "hou": "🐒",
    "gongji": "🐓",
    "ji": "🐔",
    "zhu": "🐗",
    "daxiang": "🐘",
    "xiang": "🐘",
    "zhangyu": "🐙",
    "zhang": "🐙",
    "hailuo": "🐚",
    "chongzi": "🐛",
    "chong": "🐛",
    "mayi": "🐜",
    "yi": "🐜",
    "mifeng": "🐝",
    "feng": "🐝",
    "piaochong": "🐞",
    "piao": "🐞",
    "daiyu": "🐠",
    "gui": "🐢",
    "guai": "🐢",
    "xiaoji": "🐤",
    "liao": "🐦",
    "niao": "🐦",
    "tengxun": "🐧",
    "qie": "🐧",
    "kaola": "🐨",
    "tuo": "🐫",
    "loutuo": "🐫",
    "luotuo": "🐫",
    "tun": "🐬",
    "haitun": "🐬",
    "shu": "🐭",
    "laoshu": "🐭",
    "niu": "🐮",
    "liupi": "🐮🍺",
    "laohu": "🐯",
    "hu": "🐯",
    "tuzi": "🐰",
    "tu": "🐰",
    "ao": "🐱",
    "mao": "🐱",
    "miao": "🐱",
    "long": "🐲",
    "ma": "🐴",
    "houzi": "🐵",
    "hou": "🐵",
    "hao": "🐵",
    "gou": "🐶",
    "zhu": "🐷",
    "hama": "🐸",
    "qinghua": "🐸",
    "ha": "🐸",
    "xiong": "🐻",
    "xiongmao": "🐼",
    "zhubi": "🐽",
    "kan": "👀",
    "yanjing": "👀",
    "yan": "👁",
    "er": "👂",
    "erduo": "👂",
    "bi": "👃",
    "bizi": "👃",
    "zuichun": "👄",
    "zui": "👄",
    "tian": "👅",
    "shangmian": "👆",
    "chuo": "👆",
    "zuomian": "👈",
    "zhi": "👈",
    "youmian": "👉",
    "quan": "👊",
    "bie": "👋",
    "ting": "👋",
    "buxing": "👋",
    "huishou": "👋",
    "ok": "👌",
    "haode": "👌",
    "hao": "👍",
    "damuzhi": "👍",
    "zan": "👍",
    "bang": "👍",
    "cai": "👎",
    "huai": "👎",
    "cha": "👎",
    "guzhang": "👏",
    "cuo": "👏",
    "paishou": "👏",
    "pa": "👏",
    "shuangshou": "👐",
    "huangguan": "👑",
    "caomao": "👒",
    "yanjing": "👓",
    "yifu": "👕",
    "Txu": "👕",
    "qunzi": "👗",
    "qun": "👗",
    "hanfu": "👘",
    "nei": "👙",
    "bijini": "👙",
    "nüzhuang": "👚",
    "qianbao": "👛",
    "shoutidai": "👜",
    "xie": "👞",
    "xiezi": "👞",
    "xiezi": "👟",
    "gaogenxie": "👠",
    "xuezi": "👢",
    "zuji": "👣",
    "jiao": "👣",
    "jiaoyin": "👣",
    "ren": "👤",
    "gege": "👦",
    "nansheng": "👦",
    "nanhai": "👦",
    "nühai": "👧",
    "nv": "👧",
    "nüsheng": "👧",
    "nan": "👨",
    "nanren": "👨",
    "tuzi": "👨",
    "nige": "👨🏿",
    "heiren": "👨🏿",
    "nü": "👩",
    "nüren": "👩",
    "jiaren": "👪",
    "qianshou": "👫",
    "jingcha": "👮",
    "baba": "👱",
    "laozi": "👴",
    "ye": "👴",
    "lao": "👴",
    "yeye": "👴",
    "laoren": "👴",
    "nainai": "👵",
    "xiaohai": "👶",
    "didi": "👶",
    "gongren": "👷",
    "nongmingong": "👷",
    "nvwang": "👸",
    "mo": "👻",
    "gui": "👻",
    "tianshi": "👼",
    "waixingren": "👽",
    "fennu": "👿",
    "shengqi": "👿",
    "emo": "👿",
    "si": "💀",
    "tiaowu": "💃",
    "wu": "💃",
    "kouhong": "💄",
    "jiantoufa": "💇",
    "jianfa": "💇",
    "zhen": "💉",
    "yao": "💊",
    "qin": "💋",
    "wen": "💋",
    "qinwen": "💋",
    "qingshu": "💌",
    "jiezhi": "💍",
    "zuan": "💎",
    "zuanshi": "💎",
    "xianglian": "💏",
    "xianglian": "💑",
    "jiaotang": "💒",
    "xindong": "💓",
    "xintiao": "💓",
    "ai": "💓",
    "xinsui": "💔",
    "xinxiangyin": "💕",
    "xinxinxiangyin": "💕",
    "xindong": "💗",
    "ming": "💗",
    "zhaxin": "💘",
    "xin": "💚",
    "lv": "💚",
    "deng": "💡",
    "liang": "💡",
    "nu": "💢",
    "shengqi": "💢",
    "zhadan": "💣",
    "hunshui": "💤",
    "kun": "💤",
    "shuijiao": "💤",
    "baozha": "💥",
    "zha": "💥",
    "peng": "💥",
    "shui": "💦",
    "di": "💦",
    "de": "💧",
    "shui": "💧",
    "ben": "💨",
    "feng": "💨",
    "fangpi": "💨",
    "shi": "💩",
    "shit": "💩",
    "dabian": "💩",
    "gebo": "💪",
    "li": "💪",
    "zhuang": "💪",
    "jirou": "💪",
    "ni": "💪",
    "qiang": "💪",
    "qiangzhuang": "💪",
    "xinxi": "💬",
    "meng": "💭",
    "xiangfa": "💭",
    "manfen": "💯",
    "100fen": "💯",
    "qian": "💰",
    "qiandai": "💰",
    "huilv": "💱",
    "xinyongka": "💳",
    "jie": "💳",
    "riyuan": "💴",
    "meiyuan": "💵",
    "ouyuan": "💶",
    "mai": "💸",
    "gupiao": "💹",
    "shun": "💹",
    "zuowei": "💺",
    "diannao": "💻",
    "shoutidai": "💼",
    "yingpan": "💽",
    "guangpan": "💿",
    "guangpan": "📀",
    "DVD": "📀",
    "wenjianjia": "📁",
    "zi": "📄",
    "zhi": "📄",
    "rili": "📅",
    "zengjia": "📈",
    "zengzhang": "📈",
    "zeng": "📈",
    "zengda": "📈",
    "jianshao": "📉",
    "xiajiang": "📉",
    "jiangdi": "📉",
    "jiang": "📉",
    "tuding": "📌",
    "huixingzhen": "📎",
    "chizi": "📏",
    "chi": "📏",
    "chang": "📏",
    "shuqian": "📑",
    "bijiben": "📔",
    "shu": "📕",
    "ben": "📕",
    "shu": "📖",
    "ji": "📝",
    "bianqian": "📝",
    "jilu": "📝",
    "beiwanglu": "📝",
    "dianhua": "📠",
    "leida": "📡",
    "laba": "📢",
    "laba": "📣",
    "fasong": "📤",
    "zai": "📥",
    "shoudao": "📥",
    "jieshou": "📥",
    "bao": "📦",
    "youjian": "📧",
    "shouxin": "📩",
    "xinxiang": "📫",
    "youxiang": "📮",
    "baozhi": "📰",
    "shouji": "📱",
    "guanji": "📴",
    "xinhao": "📶",
    "zhaoxiangji": "📷",
    "xiangji": "📷",
    "luxiangji": "📹",
    "dianshi": "📺",
    "shouyinji": "📻",
    "shouting": "📻",
    "fangying": "📽",
    "shangying": "📽",
    "zhongfang": "🔁",
    "danquxunhuan": "🔂",
    "xunhuan": "🔄",
    "rao": "🔄",
    "raoquan": "🔄",
    "jingyin": "🔇",
    "yinliang": "🔈",
    "laba": "🔊",
    "dianchi": "🔋",
    "chatou": "🔌",
    "fangda": "🔍",
    "fangdajing": "🔍",
    "yaochi": "🔑",
    "yaoshi": "🔑",
    "suo": "🔒",
    "shuo": "🔒",
    "jiesuo": "🔓",
    "lingdang": "🔔",
    "lingcheng": "🔔",
    "lianjie": "🔗",
    "fanhui": "🔙",
    "top": "🔝",
    "chengren": "🔞",
    "kaiche": "🔞",
    "seqing": "🔞",
    "shi": "🔟",
    "10": "🔟",
    "huo": "🔥",
    "shoudiantong": "🔦",
    "xiu": "🔧",
    "banshou": "🔧",
    "xiuli": "🔧",
    "chuizi": "🔨",
    "chui": "🔨",
    "dingyin": "🔨",
    "dao": "🔪",
    "qiang": "🔫",
    "shouqiang": "🔫",
    "xianweijing": "🔬",
    "wangyuanjing": "🔭",
    "shuijingqiu": "🔮",
    "sanchaji": "🔱",
    "hei": "🔲",
    "gezi": "🕊️",
    "ge": "🕊️",
    "yidian": "🕐",
    "erdian": "🕑",
    "sandian": "🕒",
    "sidian": "🕓",
    "wudian": "🕔",
    "liudian": "🕕",
    "qidian": "🕖",
    "badian": "🕗",
    "jiudian": "🕘",
    "shidian": "🕙",
    "shiyidian": "🕚",
    "lingdian": "🕛",
    "lazhu": "🕯",
    "dong": "🕳️",
    "taiyangjing": "🕶️",
    "zhizhu": "🕷️",
    "zhu": "🕷️",
    "zhuwang": "🕸️",
    "bi": "🖊",
    "gangbi": "🖊",
    "huabi": "🖌",
    "labi": "🖍",
    "shou": "🖐️",
    "shouzhang": "🖐️",
    "heixin": "🖤",
    "dayinji": "🖨",
    "dayin": "🖨",
    "shubiao": "🖱",
    "lajitong": "🗑",
    "bishou": "🗡",
    "shijieditu": "🗺",
    "gao": "🗻",
    "dao": "🗾",
    "shixiang": "🗿",
    "xiao": "😁",
    "xiaoku": "😂",
    "xiao": "😂",
    "kaixin": "😃",
    "xiao": "😄",
    "le": "😆",
    "zhayan": "😉",
    "weixiao": "😊",
    "se": "😍",
    "xihuan": "😍",
    "han": "😓",
    "nanguo": "😔",
    "feiwen": "😘",
    "qin": "😚",
    "tiaopi": "😜",
    "xiaren": "😥",
    "ku": "😭",
    "nanshou": "😰",
    "yun": "😵",
    "buxing": "🙅",
    "baotou": "🙆",
    "lingguangyixian": "🙇",
    "meiyankan": "🙈",
    "mengyan": "🙈",
    "buting": "🙉",
    "jinyan": "🙊",
    "bushuohua": "🙊",
    "shuangshou": "🙌",
    "jushou": "🙌",
    "zhufu": "🙏",
    "baoyou": "🙏",
    "qidao": "🙏",
    "kuai": "🚀",
    "huojian": "🚀",
    "gaotie": "🚄",
    "dongche": "🚅",
    "huoche": "🚆",
    "ditie": "🚇",
    "huochezhan": "🚉",
    "gonggongqiche": "🚌",
    "gongjiaoche": "🚌",
    "jiuhuche": "🚑",
    "jijiuche": "🚑",
    "xiaofangche": "🚒",
    "jingche": "🚓",
    "chuzuche": "🚕",
    "jiaoche": "🚗",
    "qiche": "🚗",
    "che": "🚗",
    "che": "🚙",
    "qiche": "🚙",
    "huoche": "🚚",
    "tuolaji": "🚜",
    "chuan": "🚢",
    "youlun": "🚢",
    "hai": "🚢",
    "houlvdeng": "🚥",
    "honglüdeng": "🚦",
    "men": "🚪",
    "jinzhi": "🚫",
    "lan": "🚫",
    "yan": "🧂",
    "xiyan": "🚬",
    "yan": "🚬",
    "xiangyan": "🚬",
    "zixingche": "🚲",
    "danche": "🚲",
    "zihangche": "🚲",
    "qiche": "🚴",
    "zoulu": "🚶",
    "zou": "🚶",
    "nance": "🚹",
    "nüce": "🚺",
    "yinger": "🚼",
    "matong": "🚽",
    "cesuo": "🚽",
    "cesuo": "🚾",
    "wc": "🚾",
    "xizao": "🚿",
    "linyu": "🚿",
    "paozao": "🛀",
    "xizao": "🛀",
    "yugang": "🛁",
    "shuijiao": "🛌",
    "shui": "🛌",
    "gouwudai": "🛍",
    "ling": "🛎",
    "xiangling": "🛎",
    "chuang": "🛏",
    "ting": "🛑",
    "tie": "🛠",
    "dunpai": "🛡",
    "you": "🛢",
    "weixing": "🛰️",
    "renzaoweixing": "🛰️",
    "feidie": "🛸",
    "zei": "🤑",
    "wo": "🤝",
    "woshou": "🤝",
    "bixin": "🤞",
    "chou": "🤡",
    "tu": "🤮",
    "ben": "🤯",
    "wei": "🥀",
    "shaozi": "🥄",
    "jiang": "🥇",
    "quanji": "🥊",
    "huanggua": "🥒",
    "peigen": "🥓",
    "tudou": "🥔",
    "fanshu": "🥔",
    "huluobo": "🥕",
    "luobo": "🥕",
    "guo": "🥘",
    "dan": "🥚",
    "niunai": "🥛",
    "huasheng": "🥜",
    "mihoutao": "🥝",
    "laobing": "🥞",
    "jianbing": "🥞",
    "jiaozi": "🥟",
    "kuaizi": "🥢",
    "kuai": "🥢",
    "tang": "🥣",
    "sanmingzhi": "🥪",
    "yuebing": "🥮",
    "pangxie": "🦀",
    "xie": "🦀",
    "shizi": "🦁",
    "shi": "🦁",
    "ying": "🦅",
    "laoying": "🦅",
    "yazi": "🦆",
    "ya": "🦆",
    "shayu": "🦈",
    "sha": "🦈",
    "hudie": "🦋",
    "die": "🦋",
    "xia": "🦐",
    "wuzei": "🦑",
    "zhangjinglu": "🦒",
    "banma": "🦓",
    "daishu": "🦘",
    "yingwu": "🦜",
    "huanxiong": "🦝",
    "longxia": "🦞",
    "ding": "🦟",
    "wenzi": "🦟",
    "tiane": "🦢",
    "gutou": "🦴",
    "gu": "🦴",
    "tui": "🦵",
    "zu": "🦶",
    "jiao": "🦶",
    "yachi": "🦷",
    "chi": "🦷",
    "nailao": "🧀",
    "tou": "🧑",
    "zhi": "🧠",
    "danao": "🧠",
    "bu": "🧣",
    "wa": "🧦",
    "wazi": "🧦",
    "hongbao": "🧧",
    "miehuoqi": "🧨",
    "shiguan": "🧪",
    "jiyin": "🧬",
    "DNA": "🧬",
    "zhinanzhen": "🧭",
    "suanpan": "🧮",
    "gongjuxiang": "🧰",
    "zhuan": "🧱",
    "cili": "🧲",
    "citie": "🧲",
    "ci": "🧲",
    "hangli": "🧳",
    "xijiejing": "🧴",
    "xian": "🧵",
    "maoxian": "🧶",
    "taidixiong": "🧸",
    "saozhou": "🧹",
    "sao": "🧹",
    "saoba": "🧹",
    "lanzi": "🧺",
    "weishengzhi": "🧻",
    "juanzhi": "🧻",
    "feizao": "🧼",
    "zao": "🧼",
    "haimian": "🧽",
    "shouju": "🧾",
    "fu": "🪓"
};
const elementsP = {
    "qing": "氢",
    "qin": "氢",
    "hai": "氦",
    "li": "锂",
    "ni": "锂",
    "pi": "铍",
    "peng": "硼",
    "tan": "钽",
    "dan": "氮",
    "yang": "氧",
    "fu": "氟",
    "nai": "氖",
    "na": "钠",
    "mei": "镁",
    "lv": "氯",
    "gui": "硅",
    "lin": "磷",
    "liu": "硫",
    "ya": "氩",
    "jia": "镓",
    "gai": "钙",
    "kang": "钪",
    "tai": "钛",
    "fan": "钒",
    "ge": "鿔",
    "meng": "锰",
    "tie": "铁",
    "gu": "钴",
    "nie": "镍",
    "tong": "铜",
    "xin": "锌",
    "zhe": "锗",
    "shen": "砷",
    "xi": "锡",
    "xiu": "溴",
    "ke": "氪",
    "ru": "铷",
    "si": "锶",
    "yi": "铱",
    "gao": "锆",
    "ni": "铌",
    "mu": "钼",
    "de": "锝",
    "liao": "钌",
    "lao": "铹",
    "ba": "钯",
    "yin": "铟",
    "ti": "锑",
    "di": "镝",
    "dian": "碘",
    "xian": "氙",
    "se": "铯",
    "bei": "钡",
    "lan": "镧",
    "shi": "铈",
    "pu": "镤",
    "nv": "钕",
    "po": "钋",
    "shan": "钐",
    "you": "铀",
    "ga": "钆",
    "te": "铽",
    "huo": "钬",
    "er": "铒",
    "diu": "铥",
    "lu": "镥",
    "ha": "铪",
    "wu": "钨",
    "lai": " 铼",
    "e": "锇",
    "bo": "铂",
    "jin": "金",
    "gong": "汞",
    "ta": "铊",
    "qian": "铅",
    "bi": "铋",
    "ai": "锿",
    "dong": "氡",
    "fang": "钫",
    "lei": "镭",
    "a": "锕",
    "tu": "钍",
    "bu": "钚",
    "ju": "锔",
    "pei": "锫",
    "kai": "锎",
    "fei": "镄",
    "men": "钔",
    "nuo": "锘",
    "lu": "𬬻",
    "du": "𬭊",
    "xi": "𬭳",
    "hei": "𬭶",
    "lun": "𬬭",
    "mo": "镆",
    "li": "𫟷"
};

async function chouxiang(s) {
    var h = [];
    for (let v of s) {
        h.push(v)
    }
    var cxresult = "";
    for (let index = 0; index < h.length; index++) {
        if (index < h.length && emoji[await getPinyin(h[index]) + await getPinyin(h[index + 1])] !== undefined) {
            cxresult += emoji[await getPinyin(h[index]) + await getPinyin(h[index + 1])];
            index++
        } else if (emoji[await getPinyin(h[index])] !== undefined) {
            cxresult += emoji[await getPinyin(h[index])]
        } else {
            cxresult += h[index]
        }
    }
    return cxresult
}

function rawPinyin(s) {
    console.log(s);
    var sr = [];
    for (var index in emoji) {
        if (emoji[index] === s) {
            console.log(index);
            sr.push(index)
        }
    }
    if (sr.length > 0) return sr.join("/")
    else return s
}

async function dechouxiang1(text) {
    //创建一个空字符串，用来存储替换后的文字
    var result = "";
    //创建一个变量，用来记录当前是否匹配到属性值
    var matched = false;
    //遍历文字的每个字符
    for (var i = 0; i < text.length; i++) {
        //获取当前字符
        var char = text[i];
        //如果当前字符是高代理项（头代理），并且下一个字符是低代理项（尾代理），则可能是一个emoji
        if (/[\uD800-\uDBFF]/.test(char) && /[\uDC00-\uDFFF]/.test(text[i + 1])) {
            //获取当前字符和下一个字符组成的emoji
            var emojiChar = char + text[i + 1];
            //创建一个数组，用来存储匹配到的属性名
            var names = [];
            //遍历对象的每个属性和属性值
            for (var key in emoji) {
                //如果属性值等于emoji，说明匹配到了
                if (emoji[key] === emojiChar) {
                    //将属性名添加到数组中
                    names.push(key);
                }
            }
            //如果数组不为空，说明匹配到了至少一个属性名
            if (names.length > 0) {
                //将数组中的属性名用/连接起来，作为替换的字符串
                var replaceStr = names.join("/");
                //如果之前已经匹配到了属性值，就在替换字符串前面加上_
                if (matched) {
                    replaceStr = "_" + replaceStr;
                }
                //将替换字符串添加到结果中
                result += replaceStr;
                //将匹配标志设为true
                matched = true;
                //跳过下一个字符，因为已经处理过了
                i++;
            } else {
                //如果数组为空，说明没有匹配到任何属性名，就将emoji原样添加到结果中
                result += emojiChar;
                //将匹配标志设为false
                matched = false;
                //跳过下一个字符，因为已经处理过了
                i++;
            }
        } else {
            //如果当前字符不是高代理项（头代理），或者下一个字符不是低代理项（尾代理），则不可能是一个emoji，就将字符原样添加到结果中
            result += char;
            //将匹配标志设为false
            matched = false;
        }
    }
    //返回结果
    return result;
}


async function dechouxiang2(s) {
    const h = s.split('');
    const cxresult = h.map(function (char) {
        return rawPinyin(char);
    });
    return cxresult.join('');
}

async function zhuanpinyin(text) {
    //创建一个空字符串，用来存储替换后的文字
    var result = "";
    //遍历文字的每个字符
    for (var i = 0; i < text.length; i++) {
        //获取当前字符
        var char = text[i];

        //如果当前字符是属性名，就用属性值替换它，并在后面加上__，除非是最后一个字符或者后面跟着一个标点符号
        if (pinyin[char]) {
            result += pinyin[char];
            //如果不是最后一个字符或者后面跟着一个标点符号，就加上__
            if (i < text.length - 1 && !/[。？！，；：‘’“”（）【】《》\n]/.test(text[i + 1])) {
                result += "__";
            }
        } else {
            //如果当前字符不是属性名，就保持不变
            result += char;
        }
    }
    //返回结果
    return result;
}

async function huaxue(s) {
    var h = [];
    for (let v of s) {
        h.push(v)
    }
    var cxresult = "";
    for (let index = 0; index < h.length; index++) {
        if (index < h.length && elementsP[await getPinyin(h[index]) + await getPinyin(h[index + 1])] !== undefined) {
            cxresult += elementsP[await getPinyin(h[index]) + await getPinyin(h[index + 1])];
            index++
        } else if (elementsP[await getPinyin(h[index])] !== undefined) {
            cxresult += elementsP[await getPinyin(h[index])]
        } else {
            cxresult += h[index]
        }
    }
    return cxresult
}